server {
    listen 80;

    server_name localhost;

    root /usr/share/nginx/html;

    index register.html;


    location = / {
        return 302 /register;
    }


    location = /register {
        try_files /register.html =404;
    }


    location = /login {
        try_files /login.html =404;
    }


    location = /verify-otp {
        try_files /verify-otp.html =404;
    }


    location / {
        try_files $uri $uri/ =404;
    }
}